# theme: jekyll-theme-minimal
remote_theme: anvodstudio/simpler-jekyll-theme

minima:
  skin: dark
title: My Portfolio
description: Welcome to my portfolio where I showcase my projects.

plugins:
  - jekyll-remote-theme
  - jekyll-feed
