site_name: Lewis Wood's Home Page
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lewis-wood-se
    - icon: fontawesome/brands/github
      link: https://github.com/fushipanda

copyright: Copyright &copy; 2025 Lewis Wood
